#!/bin/bash
POSTGRESQL_VERSION=${POSTGRESQL_VERSION:-12}
locale-gen --purge en_US.UTF-8 && dpkg-reconfigure --frontend=noninteractive locales && echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade -y
apt-get update && apt-get upgrade -y && apt-get install wget gnupg2 python3 curl expect-dev node-less python3-pillow python3-lxml python3-dev python3-pip python3-setuptools npm nodejs libldap2-dev libsasl2-dev libxml2-dev libxslt1-dev libjpeg-dev zlib1g-dev libfontconfig1 -y
#adding postgresql debian repo in order to access all available postgresql version
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list
apt-get update && apt-get install postgresql-${POSTGRESQL_VERSION} postgresql-server-dev-${POSTGRESQL_VERSION} -y
npm install -g less less-plugin-clean-css -y && ln -s /usr/bin/nodejs /usr/bin/node
curl -o wkhtmltox.deb -SL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb && gdebi -n wkhtmltox.deb
dpkg --force-depends -i wkhtmltox.deb
rm -rf wkhtmltox.deb
pip3 install -r ${CI_PROJECT_DIR}/requirements.txt coverage
wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz && gunzip GeoLiteCity.dat.gz && mkdir -p /usr/share/GeoIP/ && mv GeoLiteCity.dat /usr/share/GeoIP/
service postgresql restart && su - postgres -c "createuser -s flectra"
adduser --system --quiet --shell=/bin/bash --gecos 'flectra' --group flectra --home=${CI_PROJECT_DIR}
su flectra
