#!/bin/bash
locale-gen --purge en_US.UTF-8 && dpkg-reconfigure --frontend=noninteractive locales && echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
apt-get install wget postgresql postgresql-server-dev-9.5 expect-dev python-lxml curl node-less build-essential python3-pillow python3-lxml python-ldap3 python3-dev python3-pip python3-setuptools npm nodejs git libldap2-dev libsasl2-dev libxml2-dev libxslt1-dev libjpeg-dev zlib1g-dev libfontconfig1 -y
pip3 install -r ${CI_PROJECT_DIR}/requirements.txt
npm install -g less less-plugin-clean-css -y && ln -s /usr/bin/nodejs /usr/bin/node
curl -o wkhtmltox.deb -SL https://downloads.wkhtmltopdf.org/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
echo '5c509de79121e96908794ebcb9d16647a9385e1d wkhtmltox.deb' | sha1sum -c -
dpkg --force-depends -i wkhtmltox.deb
pip3 install coverage coveralls codecov simplejson pyserial pyyaml unittest2 pyopenssl>=16.2.0
wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz && gunzip GeoLiteCity.dat.gz && mkdir -p /usr/share/GeoIP/ && mv GeoLiteCity.dat /usr/share/GeoIP/
service postgresql restart && su - postgres -c "createuser -s flectra"
adduser --system --quiet --shell=/bin/bash --gecos 'flectra' --group flectra --home=${CI_PROJECT_DIR}